Add cask existence checking in cask-check-updates

diff --git a/cask-check-updates b/cask-check-updates
--- a/cask-check-updates
+++ b/cask-check-updates
@@ -2,13 +2,13 @@
 #
 # Find outdated casks and their latest versions.
 #
-# Version:         0.3.1
+# Version:         0.3.2
 # License:         The Unlicense (Public Domain)
 # Author:          Victor Popkov <victor@popkov.me>
 # Last modified:   26.05.2016
 
 # Constants and globals
-readonly VERSION='0.3.1'
+readonly VERSION='0.3.2'
 readonly PROGRAM=$(basename "$0")
 readonly TEMP_DIR=$(mktemp -d)
 readonly BROWSER_HEADERS='User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36'
@@ -92,6 +92,17 @@ usage() {
       -h, --help                           Show this help." | sed -E 's/^ {4}//'
 }
 
+# Divider to separate output in terminal.
+#
+# Globals:
+#   COLUMNS
+#
+# Returns the full-width terminal divider.
+divide() {
+  if [[ $(which hr) ]]; then hr '-'
+  else printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -; fi
+}
+
 # check if 'xmlstarlet' and 'jq' are installed and configured
 if [[ ! $(which 'xmlstarlet') ]] || [[ ! $(which 'jq') ]]; then
   case "${OSTYPE}" in
@@ -173,26 +184,19 @@ while [[ "$1" ]]; do
       syntax_error "unrecognized option: $1"
       ;;
     *)
-      CASKS=("${@/.rb/}")
-      readonly CASKS
-      [[ "${#CASKS[@]}" -eq 1 ]] && SHOW_ALL='true'
-      readonly SHOW_ALL
+      for arg in "$@"; do
+        cask="${arg/.rb}"
+        [[ -f "${cask}.rb" ]] && CASKS+=("${cask}") || printf "Cask '%s' not found\n" "${cask}"
+      done
+      [[ "$#" != "${#CASKS[@]}" ]] && [[ "${#CASKS[@]}" -eq 0 ]] && exit 1
+
+      divide
+      readonly SHOW_ALL='true'
       break
       ;;
   esac
   shift
 done
-
-# Divider to separate output in terminal.
-#
-# Globals:
-#   COLUMNS
-#
-# Returns the full-width terminal divider.
-divide() {
-  if [[ $(which hr) ]]; then hr '-'
-  else printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -; fi
-}
 
 # Get value/values of a cask stanza.
 #
@@ -811,10 +815,10 @@ show_review() {
 review_cask_versions() {
   local -a versions appcasts checkpoints urls latest
   local -i versions_max_length appcasts_counter i status
-  local line version appcast checkpoint url out code content latest_checkpoint latest_version suggested_version suggested_latest_version latest_url review_name review_value
+  local cask values line version appcast checkpoint url out code content latest_checkpoint latest_version suggested_version suggested_latest_version latest_url review_name review_value
 
-  local -r cask="$1"
-  local -r values=$(get_cask_version_appcast_checkpoint_url "${cask}")
+  readonly cask="$1"
+  readonly values=$(get_cask_version_appcast_checkpoint_url "${cask}")
 
   IFS=$'\n' read -rd '' -a lines <<< "${values}"
 
@@ -910,10 +914,10 @@ review_cask_versions() {
 review_cask_appcasts() {
   local -a appcasts checkpoints
   local -i appcasts_max_length i
-  local version appcast checkpoint out code content latest_checkpoint latest_version review_name review_value status
+  local cask values version appcast checkpoint out code content latest_checkpoint latest_version review_name review_value status
 
-  local -r cask="$1"
-  local -r values=$(get_cask_version_appcast_checkpoint_url "${cask}")
+  readonly cask="$1"
+  readonly values=$(get_cask_version_appcast_checkpoint_url "${cask}")
 
   IFS=$'\n' read -rd '' -a lines <<< "${values}"
 
